configs.AndAgent
A,B
AND_OUT
configs.OrAgent
A,B
OR_OUT
configs.XorAgent
A,B
XOR_OUT
configs.NandAgent
A,B
NAND_OUT
configs.NorAgent
A,B
NOR_OUT
configs.XnorAgent
A,B
XNOR_OUT
configs.NotAgent
A
NOT_A
configs.MajorityAgent
A,B,C
MAJ_OUT
