configs.SubAgent
A,B
SUB_OUT
configs.MulAgent
A,B
MUL_OUT
configs.DivAgent
A,B
DIV_OUT
configs.ModAgent
A,B
MOD_OUT
configs.PowAgent
A,B
POW_OUT
configs.MinAgent
A,B
MIN_OUT
configs.MaxAgent
A,B
MAX_OUT
configs.AvgAgent
A,B
AVG_OUT
